In [1]:
import numpy as np

In [3]:
arr = np.array([1,3,4])
print(arr)

[1 3 4]


In [5]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.full((8,9),2)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
myarr.size

9

In [25]:
myarr.ndim

2

In [27]:
myarr.dtype

dtype('int32')

In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
mask = arr[:,0] > 3

In [19]:
mask2 = arr[:,1] < 10

In [21]:
print(arr[mask & mask2])

[[4 5 6]
 [7 8 9]]


In [23]:
arr.shape


(3, 3)