In [3]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
flat = arr.flatten()

In [12]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
flat[3:6]

array([4, 5, 6])

In [18]:
flat[:3]      # 0 to 2

array([1, 2, 3])

In [20]:
flat[::2]

array([1, 3, 5, 7, 9])

In [22]:
flat[3] = 13

In [24]:
flat


array([ 1,  2,  3, 13,  5,  6,  7,  8,  9])

In [44]:
b=flat[3:6]

In [46]:
# Slicing return view not copy   

# To work with copy
b=flat[3:6].copy()

In [48]:
# Fancy indexing

flat[[2,4,6]]

array([ 3, 12,  7])

In [50]:
#     solving Exercise

In [54]:
#Create a 3*3 array filled with random numbers and print its shape


In [56]:
arr = np.random.rand(3,3)

In [58]:
arr

array([[0.3669213 , 0.31471493, 0.26292702],
       [0.68596977, 0.3226022 , 0.4116525 ],
       [0.94944379, 0.10326656, 0.70042212]])

In [60]:
# Convert an array of floats [1.1,2.2,3.3,...] into integers.

In [70]:
arr2 = np.array([1.1,2.2,3.3])
print(type(arr2))

<class 'numpy.ndarray'>


In [72]:
arr_int = arr2.astype(int);

In [78]:
print(arr_int)

[1 2 3]


In [80]:
#Use Fancy indexing to extract even numbers from [1,2,3,4,5,6]

In [90]:
arr = np.array([1,2,3,4,5,6,7,8,9])
even_arr=arr[1::2]
even=arr[arr%2 == 0]
print(even_arr)
print(even)

[2 4 6 8]
[2 4 6 8]


In [92]:
# Reshape a 1d array of size 9 into a 3*3 matrix

In [96]:
reshaped = arr.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
# Use boolean masking to filter numbers greater than 50 in an array

In [102]:
arr3 = np.array([1,3,50,60,40,8,7,5])
arr_mask=arr3>50
print(arr3[arr_mask])

[60]
