In [3]:
import numpy as np
import time

In [43]:
#Using Python list

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(add[0:10])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.37619495391845703


In [45]:
#Using Numpy array

size = 1_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1+l2
end = time.time()

print(add[0:10])
print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.044198036193847656


In [47]:
# 1D Array

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [51]:
# 2D array

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
# Checking type and Shape

print("Type :",type(arr1))
print("Shape :",arr2.shape)

Type : <class 'numpy.ndarray'>
Shape : (2, 5)


In [55]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size :",sys.getsizeof(list_data)*len(list_data), "bytes")
print("Numpy Array size :",numpy_data.nbytes, "bytes")

Python list size : 8056000 bytes
Numpy Array size : 4000 bytes


In [81]:
#           Vectorization - No more loops!

#Python list (loop-based)
size = 1_000_00
l1 = list(range(size))
start = time.time()
list_squares = [x ** 2 for x in l1]
end = time.time()
print(end-start)

#Numpy (Vectorized)  it use SIMD (Single instruction , multiple Data)
arr1 = np.array(l1)
start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print( end - start )


0.01707768440246582
0.002006053924560547


In [85]:
# Create a numpy array range from 10 to 100
arr = np.arange(10,101)
print(arr)
print(arr.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
(91,)
